const BASE = '/assets/eigo-quest';

export const EQ_ASSETS = {
  app: {
    logo: `${BASE}/app/app-logo.png`,
    logoMark: `${BASE}/app/logo-mark.png`,
    icon192: `${BASE}/app/app-icon-192.png`,
    icon512: `${BASE}/app/app-icon-512.png`,
  },
  ui: {
    appLogo: `${BASE}/ui/app-logo.png`,
    bookIcon: `${BASE}/ui/book-icon.png`,
    coinIcon: `${BASE}/ui/coin-icon.png`,
    flameStreak: `${BASE}/ui/flame-streak.png`,
    goldButton: `${BASE}/ui/gold-button.png`,
    grammarScroll: `${BASE}/ui/grammar-scroll.png`,
    grammarScrollWide: `${BASE}/ui/grammar-scrol2l.png`,
    iconStudy: `${BASE}/ui/icon-study.png`,
    quizScroll: `${BASE}/ui/quiz-scroll.png`,
    reviewGlass: `${BASE}/ui/review-glass.png`,
    wordBook: `${BASE}/ui/word-book.png`,
    wordBookAlt: `${BASE}/ui/word-bo1ok.png`,
    bottomNavFrame: `${BASE}/ui/bottom-nav-frame.png`,
  },
  nav: {
    home: `${BASE}/nav/nav-home.png`,
    map: `${BASE}/nav/nav-map.png`,
    study: `${BASE}/nav/nav-study.png`,
    cards: `${BASE}/nav/nav-cards.png`,
    more: `${BASE}/nav/nav-more.png`,
    homeGold: `${BASE}/nav/nav_icons_equal_10png/nav-home-gold.png`,
    homeBlue: `${BASE}/nav/nav_icons_equal_10png/nav-home-blue.png`,
    mapGold: `${BASE}/nav/nav_icons_equal_10png/nav-map-gold.png`,
    mapBlue: `${BASE}/nav/nav_icons_equal_10png/nav-map-blue.png`,
    studyGold: `${BASE}/nav/nav_icons_equal_10png/nav-study-gold.png`,
    studyBlue: `${BASE}/nav/nav_icons_equal_10png/nav-study-blue.png`,
    cardsGold: `${BASE}/nav/nav_icons_equal_10png/nav-card-gold.png`,
    cardsBlue: `${BASE}/nav/nav_icons_equal_10png/nav-card-blue.png`,
    moreGold: `${BASE}/nav/nav_icons_equal_10png/nav-more-gold.png`,
    moreBlue: `${BASE}/nav/nav_icons_equal_10png/nav-more-blue.png`,
  },
  bg: {
    learningHub: `${BASE}/learning-hub/上の背景.png`,
    wordLibrary: `${BASE}/learning-hub/単語図書館.png`,
    grammarTemple: `${BASE}/learning-hub/文法の神殿.png`,
    grammarPractice: `${BASE}/learning-hub/文法練習.png`,
    eikenQuest: `${BASE}/learning-hub/英検クエスト.png`,
    eikenReal: `${BASE}/learning-hub/英検本番形式.png`,
    review: `${BASE}/review/review-banner.png`,
  },
  icons: {
    home: `${BASE}/icons/icon-home.png`,
    map: `${BASE}/icons/icon-map.png`,
    study: `${BASE}/icons/icon-study.png`,
    card: `${BASE}/icons/icon-card.png`,
    more: `${BASE}/icons/icon-more.png`,
    quiz: `${BASE}/icons/icon-quiz.png`,
    review: `${BASE}/icons/icon-review.png`,
    grammar: `${BASE}/icons/icon-grammar.png`,
    word: `${BASE}/icons/icon-word.png`,
  },
  spirit: {
    idle: `${BASE}/spirit_assets/idle.png`,
    happy: `${BASE}/spirit_assets/happy.png`,
    talk: `${BASE}/spirit_assets/talk.png`,
    dance: `${BASE}/spirit_assets/dance.png`,
    sad: `${BASE}/spirit_assets/sad.png`,
  },
};
