-- PostgreSQL migration for Phase 6B. Run after verifying duplicate
-- (child_id, hero_id) rows have been repaired, otherwise the unique index can fail.

CREATE TABLE IF NOT EXISTS child_heroes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    child_id INTEGER NOT NULL REFERENCES children (id) ON UPDATE CASCADE ON DELETE CASCADE,
    hero_id INTEGER NOT NULL REFERENCES heroes (id) ON UPDATE CASCADE ON DELETE CASCADE,
    hero_code TEXT,
    awarded_world_id TEXT,
    awarded_stage_number INTEGER,
    reward_type TEXT NOT NULL DEFAULT 'stage',
    awarded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE child_heroes ADD COLUMN IF NOT EXISTS hero_code TEXT;
ALTER TABLE child_heroes ADD COLUMN IF NOT EXISTS awarded_world_id TEXT;
ALTER TABLE child_heroes ADD COLUMN IF NOT EXISTS awarded_stage_number INTEGER;
ALTER TABLE child_heroes ADD COLUMN IF NOT EXISTS reward_type TEXT NOT NULL DEFAULT 'stage';
ALTER TABLE child_heroes ADD COLUMN IF NOT EXISTS awarded_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE child_heroes ADD COLUMN IF NOT EXISTS created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE child_heroes ADD COLUMN IF NOT EXISTS updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE child_heroes AS child_hero
SET hero_code = heroes.code
FROM heroes
WHERE child_hero.hero_id = heroes.id
  AND (child_hero.hero_code IS NULL OR child_hero.hero_code = '');

CREATE UNIQUE INDEX IF NOT EXISTS idx_child_heroes_unique_child_hero
ON child_heroes (child_id, hero_id);

CREATE INDEX IF NOT EXISTS idx_child_heroes_child
ON child_heroes (child_id, awarded_at);

CREATE INDEX IF NOT EXISTS idx_child_heroes_stage
ON child_heroes (child_id, awarded_world_id, awarded_stage_number);
