export const eigoQuestCards = [
  {
    id: 'wind-spirit-breeze',
    worldId: 'wind',
    nameJa: 'そよ風の精霊',
    nameZh: '微风精灵',
    type: 'spirit',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/wind-spirit-breeze.png',
    descriptionJa: '発音を聞き分ける力をくれる、風の小さな精霊。',
    unlockCondition: '風の区域 Stage 1 をクリア',
    reviewMode: 'listening',
  },
  {
    id: 'wind-monster-gust',
    worldId: 'wind',
    nameJa: '突風モンスター',
    nameZh: '疾风怪物',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/wind-monster-gust.png',
    descriptionJa: 'すばやい単語確認が得意な風のモンスター。',
    unlockCondition: '風の区域 Stage 2 をクリア',
    reviewMode: 'flashcard',
  },
  {
    id: 'wind-guardian-skyrabbit',
    worldId: 'wind',
    nameJa: '空うさぎの守護者',
    nameZh: '天空兔守护者',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wind-guardian-skyrabbit.png',
    descriptionJa: '聞く・読む・声に出す練習を見守る守護者。',
    unlockCondition: '風の区域 Stage 5 をクリア',
    reviewMode: 'mixed',
  },
  {
    id: 'wind-boss-tempest',
    worldId: 'wind',
    nameJa: '嵐の王',
    nameZh: '风暴之王',
    type: 'boss',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/wind-boss-tempest.png',
    descriptionJa: '風の区域を守るボス。音の記憶を試してくる。',
    unlockCondition: '風の区域 Boss Stage をクリア',
    reviewMode: 'boss',
  },
  {
    id: 'fire-spirit-spark',
    worldId: 'fire',
    nameJa: '火花の精霊',
    nameZh: '火花精灵',
    type: 'spirit',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/fire-spirit-spark.png',
    descriptionJa: 'クイズに挑む気持ちを燃やしてくれる精霊。',
    unlockCondition: '火の山 Stage 1 をクリア',
    reviewMode: 'quiz',
  },
  {
    id: 'fire-monster-lava',
    worldId: 'fire',
    nameJa: '溶岩モンスター',
    nameZh: '熔岩怪物',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/fire-monster-lava.png',
    descriptionJa: '覚えた単語を熱くチェックする火のモンスター。',
    unlockCondition: '火の山 Stage 3 をクリア',
    reviewMode: 'multipleChoice',
  },
  {
    id: 'fire-guardian-phoenix',
    worldId: 'fire',
    nameJa: 'フェニックスの守護者',
    nameZh: '凤凰守护者',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/fire-guardian-phoenix.png',
    descriptionJa: 'まちがえても何度でも立ち上がる力をくれる。',
    unlockCondition: '火の山 Stage 6 をクリア',
    reviewMode: 'wrongWords',
  },
  {
    id: 'fire-boss-inferno',
    worldId: 'fire',
    nameJa: '業火の王',
    nameZh: '业火之王',
    type: 'boss',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/fire-boss-inferno.png',
    descriptionJa: '火の山のボス。すばやい正解を求めてくる。',
    unlockCondition: '火の山 Boss Stage をクリア',
    reviewMode: 'boss',
  },
  {
    id: 'thunder-spirit-static',
    worldId: 'thunder',
    nameJa: '静電気の精霊',
    nameZh: '静电精灵',
    type: 'spirit',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/thunder-spirit-static.png',
    descriptionJa: '選択肢を見てすぐ判断する力をくれる。',
    unlockCondition: '雷の塔 Stage 1 をクリア',
    reviewMode: 'speedQuiz',
  },
  {
    id: 'thunder-monster-bolt',
    worldId: 'thunder',
    nameJa: '稲妻モンスター',
    nameZh: '闪电怪物',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/thunder-monster-bolt.png',
    descriptionJa: '一瞬で答えを選ぶ練習にぴったりのモンスター。',
    unlockCondition: '雷の塔 Stage 4 をクリア',
    reviewMode: 'multipleChoice',
  },
  {
    id: 'thunder-guardian-owl',
    worldId: 'thunder',
    nameJa: '雷ふくろうの守護者',
    nameZh: '雷鸮守护者',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/thunder-guardian-owl.png',
    descriptionJa: '正確さとスピードを両方見守ってくれる。',
    unlockCondition: '雷の塔 Stage 7 をクリア',
    reviewMode: 'timedReview',
  },
  {
    id: 'thunder-boss-stormlord',
    worldId: 'thunder',
    nameJa: '雷鳴の王',
    nameZh: '雷鸣之王',
    type: 'boss',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/thunder-boss-stormlord.png',
    descriptionJa: '雷の塔のボス。迷わず答える力を試してくる。',
    unlockCondition: '雷の塔 Boss Stage をクリア',
    reviewMode: 'boss',
  },
  {
    id: 'wood-spirit-sprout',
    worldId: 'wood',
    nameJa: '新芽の精霊',
    nameZh: '新芽精灵',
    type: 'spirit',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/wood-spirit-sprout.png',
    descriptionJa: '例文から意味を育てる森の精霊。',
    unlockCondition: '木の森 Stage 1 をクリア',
    reviewMode: 'example',
  },
  {
    id: 'wood-monster-vine',
    worldId: 'wood',
    nameJa: 'つる草モンスター',
    nameZh: '藤蔓怪物',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/wood-monster-vine.png',
    descriptionJa: '言葉と言葉のつながりをからめ取るモンスター。',
    unlockCondition: '木の森 Stage 3 をクリア',
    reviewMode: 'sentence',
  },
  {
    id: 'wood-guardian-stag',
    worldId: 'wood',
    nameJa: '森鹿の守護者',
    nameZh: '森林鹿守护者',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wood-guardian-stag.png',
    descriptionJa: '文章の中で単語を使う力を守ってくれる。',
    unlockCondition: '木の森 Stage 6 をクリア',
    reviewMode: 'cloze',
  },
  {
    id: 'wood-boss-ancienttree',
    worldId: 'wood',
    nameJa: '古樹の王',
    nameZh: '古树之王',
    type: 'boss',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/wood-boss-ancienttree.png',
    descriptionJa: '木の森のボス。例文理解を深く試してくる。',
    unlockCondition: '木の森 Boss Stage をクリア',
    reviewMode: 'boss',
  },
  {
    id: 'rock-spirit-pebble',
    worldId: 'rock',
    nameJa: '小石の精霊',
    nameZh: '小石精灵',
    type: 'spirit',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/rock-spirit-pebble.png',
    descriptionJa: '毎日の積み重ねを応援する岩の精霊。',
    unlockCondition: '岩の谷 Stage 1 をクリア',
    reviewMode: 'dailyReview',
  },
  {
    id: 'rock-monster-boulder',
    worldId: 'rock',
    nameJa: '大岩モンスター',
    nameZh: '巨岩怪物',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/rock-monster-boulder.png',
    descriptionJa: '苦手な単語をしっかり受け止めるモンスター。',
    unlockCondition: '岩の谷 Stage 4 をクリア',
    reviewMode: 'wrongWords',
  },
  {
    id: 'rock-guardian-golem',
    worldId: 'rock',
    nameJa: '石像の守護者',
    nameZh: '石像守护者',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/rock-guardian-golem.png',
    descriptionJa: '弱点復習をこつこつ支えてくれる守護者。',
    unlockCondition: '岩の谷 Stage 7 をクリア',
    reviewMode: 'weakness',
  },
  {
    id: 'rock-boss-mountain',
    worldId: 'rock',
    nameJa: '山脈の王',
    nameZh: '山脉之王',
    type: 'boss',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/rock-boss-mountain.png',
    descriptionJa: '岩の谷のボス。積み重ねた記憶を試してくる。',
    unlockCondition: '岩の谷 Boss Stage をクリア',
    reviewMode: 'boss',
  },
  {
    id: 'shadow-spirit-mist',
    worldId: 'shadow',
    nameJa: '影霧の精霊',
    nameZh: '影雾精灵',
    type: 'spirit',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/shadow-spirit-mist.png',
    descriptionJa: 'まぎらわしい単語を見分ける力をくれる。',
    unlockCondition: '影の迷宮 Stage 1 をクリア',
    reviewMode: 'synonym',
  },
  {
    id: 'shadow-monster-mimic',
    worldId: 'shadow',
    nameJa: 'まねっこモンスター',
    nameZh: '模仿怪物',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/shadow-monster-mimic.png',
    descriptionJa: '似た言葉を使って迷わせる影のモンスター。',
    unlockCondition: '影の迷宮 Stage 3 をクリア',
    reviewMode: 'antonym',
  },
  {
    id: 'shadow-guardian-cat',
    worldId: 'shadow',
    nameJa: '影ねこの守護者',
    nameZh: '影猫守护者',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/shadow-guardian-cat.png',
    descriptionJa: '類義語と対義語の迷路を案内してくれる。',
    unlockCondition: '影の迷宮 Stage 6 をクリア',
    reviewMode: 'vocabExpansion',
  },
  {
    id: 'shadow-boss-nightmare',
    worldId: 'shadow',
    nameJa: '夜影の王',
    nameZh: '夜影之王',
    type: 'boss',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/shadow-boss-nightmare.png',
    descriptionJa: '影の迷宮のボス。似た意味と反対の意味を試してくる。',
    unlockCondition: '影の迷宮 Boss Stage をクリア',
    reviewMode: 'boss',
  },
  {
    id: 'water-spirit-drop',
    worldId: 'water',
    nameJa: '水滴の精霊',
    nameZh: '水滴精灵',
    type: 'spirit',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/water-spirit-drop.png',
    descriptionJa: '音声を聞いて意味につなげる力をくれる。',
    unlockCondition: '水の港 Stage 1 をクリア',
    reviewMode: 'listening',
  },
  {
    id: 'water-monster-wave',
    worldId: 'water',
    nameJa: '波乗りモンスター',
    nameZh: '乘浪怪物',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/water-monster-wave.png',
    descriptionJa: 'リズムよく音声問題に取り組ませてくれる。',
    unlockCondition: '水の港 Stage 4 をクリア',
    reviewMode: 'audioQuiz',
  },
  {
    id: 'water-guardian-mermaid',
    worldId: 'water',
    nameJa: '水の歌姫',
    nameZh: '水之歌姬',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/water-guardian-mermaid.png',
    descriptionJa: 'リスニング音声と英文を結びつける守護者。',
    unlockCondition: '水の港 Stage 7 をクリア',
    reviewMode: 'eikenListening',
  },
  {
    id: 'water-boss-leviathan',
    worldId: 'water',
    nameJa: '深海の王',
    nameZh: '深海之王',
    type: 'boss',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/water-boss-leviathan.png',
    descriptionJa: '水の港のボス。長い音声理解を試してくる。',
    unlockCondition: '水の港 Boss Stage をクリア',
    reviewMode: 'boss',
  },
  {
    id: 'light-spirit-glow',
    worldId: 'light',
    nameJa: '光粒の精霊',
    nameZh: '光粒精灵',
    type: 'spirit',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/light-spirit-glow.png',
    descriptionJa: '文法のポイントを明るく照らしてくれる。',
    unlockCondition: '光の城 Stage 1 をクリア',
    reviewMode: 'grammar',
  },
  {
    id: 'light-monster-prism',
    worldId: 'light',
    nameJa: 'プリズムモンスター',
    nameZh: '棱镜怪物',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/light-monster-prism.png',
    descriptionJa: '文の形をいろいろな角度から見せてくれる。',
    unlockCondition: '光の城 Stage 3 をクリア',
    reviewMode: 'grammarForm',
  },
  {
    id: 'light-guardian-knight',
    worldId: 'light',
    nameJa: '光の騎士',
    nameZh: '光之骑士',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/light-guardian-knight.png',
    descriptionJa: '英検チャレンジに挑む勇気をくれる守護者。',
    unlockCondition: '光の城 Stage 6 をクリア',
    reviewMode: 'eiken',
  },
  {
    id: 'light-boss-archangel',
    worldId: 'light',
    nameJa: '暁光の王',
    nameZh: '晓光之王',
    type: 'boss',
    rarity: 'LEGEND',
    image: '/assets/eigo-quest/cards/light-boss-archangel.png',
    descriptionJa: '光の城の最終ボス。すべての学習の力を試してくる。',
    unlockCondition: '光の城 Boss Stage をクリア',
    reviewMode: 'finalBoss',
  },
];

export default eigoQuestCards;
