export const eigoQuestWorlds = [
  {
    id: 'wind',
    nameJa: '風の区域',
    nameZh: '风之区域',
    subtitleJa: '音を聞き取り、単語をすばやく覚える冒険',
    themeColor: '#35d9ff',
    backgroundImage: '/assets/eigo-quest/worlds/wind.png',
    icon: '風',
    learningFocus: 'リスニング・発音・単語カード',
    stages: 10,
  },
  {
    id: 'fire',
    nameJa: '火の山',
    nameZh: '火之山',
    subtitleJa: 'クイズで知識を燃やして強くする冒険',
    themeColor: '#ff6b8a',
    backgroundImage: '/assets/eigo-quest/worlds/fire.png',
    icon: '火',
    learningFocus: '単語クイズ・復習',
    stages: 10,
  },
  {
    id: 'thunder',
    nameJa: '雷の塔',
    nameZh: '雷之塔',
    subtitleJa: 'すばやく選び、正確に答える冒険',
    themeColor: '#ffd35a',
    backgroundImage: '/assets/eigo-quest/worlds/thunder.png',
    icon: '雷',
    learningFocus: '四択問題・瞬間判断',
    stages: 10,
  },
  {
    id: 'wood',
    nameJa: '木の森',
    nameZh: '木之森林',
    subtitleJa: '例文を読んで言葉の使い方を育てる冒険',
    themeColor: '#54e6a8',
    backgroundImage: '/assets/eigo-quest/worlds/wood.png',
    icon: '木',
    learningFocus: '例文・意味理解',
    stages: 10,
  },
  {
    id: 'rock',
    nameJa: '岩の谷',
    nameZh: '岩之谷',
    subtitleJa: 'こつこつ積み上げて苦手をなくす冒険',
    themeColor: '#b7c0dd',
    backgroundImage: '/assets/eigo-quest/worlds/rock.png',
    icon: '岩',
    learningFocus: 'まちがい直し・弱点復習',
    stages: 10,
  },
  {
    id: 'shadow',
    nameJa: '影の迷宮',
    nameZh: '影之迷宫',
    subtitleJa: 'まぎらわしい言葉を見分ける冒険',
    themeColor: '#7b55ff',
    backgroundImage: '/assets/eigo-quest/worlds/shadow.png',
    icon: '影',
    learningFocus: '類義語・対義語',
    stages: 10,
  },
  {
    id: 'water',
    nameJa: '水の港',
    nameZh: '水之港',
    subtitleJa: '音声と文章をつなげて理解する冒険',
    themeColor: '#35d9ff',
    backgroundImage: '/assets/eigo-quest/worlds/water.png',
    icon: '水',
    learningFocus: 'リスニング・英検真題',
    stages: 10,
  },
  {
    id: 'light',
    nameJa: '光の城',
    nameZh: '光之城',
    subtitleJa: '文法と英検に挑戦する最後の冒険',
    themeColor: '#ffd35a',
    backgroundImage: '/assets/eigo-quest/worlds/light.png',
    icon: '光',
    learningFocus: '文法練習・英検チャレンジ',
    stages: 10,
  },
];

export default eigoQuestWorlds;
