export const eigoQuestCards = [
  // ==========================================
  // FIRE WORLD (火の世界) - Total: 10 Cards
  // ==========================================
  {
    id: 'fire-guardian-hephaestus',
    worldId: 'fire',
    nameJa: 'ヘーパイストス',
    nameZh: '赫菲斯托斯',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/fire-guardian1.png',
    descriptionJa: '鍛冶と炎を司る神。神々の武具を鍛え、灼熱の炉で世界を支える。',
    unlockCondition: '火の山 Stage 1 をクリア',
    reviewMode: 'quiz',
  },
  {
    id: 'fire-monster-chimera',
    worldId: 'fire',
    nameJa: 'キマイラ',
    nameZh: '奇美拉',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/fire-guardian2.png',
    descriptionJa: '獅子の頭、山羊の胴、蛇の尾を持つ炎の魔獸。口から灼熱の炎を吐き、戦場を恐怖で包む。',
    unlockCondition: '火の山 Stage 2 をクリア',
    reviewMode: 'multipleChoice',
  },
  {
    id: 'fire-guardian-loki',
    worldId: 'fire',
    nameJa: 'ロキ',
    nameZh: '洛基',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/fire-guardian3.png',
    descriptionJa: '炎と策略をまとう北欧の神。变幻自在の知恵で敵を惑わし、混乱を支配する。',
    unlockCondition: '火の山 Stage 3 をクリア',
    reviewMode: 'wrongWords',
  },
  {
    id: 'fire-guardian-agni',
    worldId: 'fire',
    nameJa: 'アグニ',
    nameZh: '阿耆尼',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/fire/fire-guardian5.png',
    descriptionJa: '聖なる火を司るインドの神。浄化と再生の炎で闇を払い、祈りを天へ届ける。',
    unlockCondition: '火の山 Stage 4 をクリア',
    reviewMode: 'speedQuiz',
  },
  {
    id: 'fire-monster-ravana',
    worldId: 'fire',
    nameJa: 'ラーヴァナ',
    nameZh: '罗波那',
    type: 'monster',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/fire/fire-guardian6.png',
    descriptionJa: '猛火のごとき力を宿す魔王。圧倒的な戦意と魔力で敵を焼き尽くす。',
    unlockCondition: '火の山 Stage 5 をクリア',
    reviewMode: 'synonym',
  },
  {
    id: 'fire-guardian-lvbu',
    worldId: 'fire',
    nameJa: '呂布',
    nameZh: '吕布',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/fire/fire-guardian7.png',
    descriptionJa: '烈火のような武勇を誇る三国の豪傑。ひとたび戦えば、その猛威は誰にも止められない。',
    unlockCondition: '火の山 Stage 6 をクリア',
    reviewMode: 'timedReview',
  },
  {
    id: 'fire-guardian-zhurong',
    worldId: 'fire',
    nameJa: '祝融',
    nameZh: '祝融',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/fire/fire-guardian8.png',
    descriptionJa: '炎を統べる中国神話の神。赤熱の業火で邪を灭し、威厳をもって天を照らす。',
    unlockCondition: '火の山 Stage 7 をクリア',
    reviewMode: 'challenge',
  },
  {
    id: 'fire-guardian-nobunaga',
    worldId: 'fire',
    nameJa: '織田信長',
    nameZh: '织田信长',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/fire/fire-guardian9.png',
    descriptionJa: '炎のごとき革新で時代を切り開く戦国の覇者。激しい決断力で戦場を制する。',
    unlockCondition: '火の山 Stage 8 をクリア',
    reviewMode: 'hardcore',
  },
  {
    id: 'fire-guardian-kagutsuchi',
    worldId: 'fire',
    nameJa: 'カグツチ',
    nameZh: '迦具土',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/fire/fire-guardian10.png',
    descriptionJa: '日本神話における火の神。生まれながらに強大な火力を宿し、創造と破壊をもたらす。',
    unlockCondition: '火の山 Stage 9 をクリア',
    reviewMode: 'vocabExpansion',
  },
  {
    id: 'fire-boss-surtr',
    worldId: 'fire',
    nameJa: 'スルト',
    nameZh: '苏尔特尔',
    type: 'boss',
    rarity: 'LEGEND',
    image: '/assets/eigo-quest/cards/fire/fire-guardian4.png',
    descriptionJa: '終末の炎を振るう巨人王。燃える剣で世界を焼き尽くす破滅の化身。',
    unlockCondition: '火の山 Boss Stage をクリア',
    reviewMode: 'boss',
  },

  // ==========================================
  // LIGHT WORLD (光の世界) - Total: 10 Cards
  // ==========================================
  {
    id: 'light-guardian-apollo',
    worldId: 'light',
    nameJa: 'アポロン',
    nameZh: '阿波罗',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/light-guardian1.png',
    descriptionJa: '光明と芸術を司るギリシャの神。太陽の車を駆り、世界に真実の光をもたらす。',
    unlockCondition: '光の城 Stage 1 をクリア',
    reviewMode: 'grammar',
  },
  {
    id: 'light-monster-sphinx',
    worldId: 'light',
    nameJa: 'スフィンクス',
    nameZh: '斯芬克斯',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/light-guardian2.png',
    descriptionJa: '聖なる光の試練を与える守護獣。知恵の謎解きを突きつけ、旅人の覚悟を試す。',
    unlockCondition: '光の城 Stage 2 をクリア',
    reviewMode: 'grammarForm',
  },
  {
    id: 'light-guardian-baldr',
    worldId: 'light',
    nameJa: 'バルドル',
    nameZh: '巴德尔',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/light-guardian3.png',
    descriptionJa: '光と気高さをまとう北欧の神。すべての人に愛され、純粋な輝きで绝望を払う。',
    unlockCondition: '光の城 Stage 3 をクリア',
    reviewMode: 'quiz',
  },
  {
    id: 'light-guardian-amaterasu',
    worldId: 'light',
    nameJa: 'アマテラス',
    nameZh: '天照大神',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/light-guardian4.png',
    descriptionJa: '高天原を統べる日本神話の主神。あまねく世界を照らし、八百万の神々に秩序を与える。',
    unlockCondition: '光の城 Stage 4 をクリア',
    reviewMode: 'eikenListening',
  },
  {
    id: 'light-guardian-indra',
    worldId: 'light',
    nameJa: 'インドラ',
    nameZh: '因陀罗',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/light-guardian5.png',
    descriptionJa: '雷霆と光明を司るインドの英雄神。神々の王として、邪悪な闇の军势を打ち砕く。',
    unlockCondition: '光の城 Stage 5 をクリア',
    reviewMode: 'eiken',
  },
  {
    id: 'light-guardian-arthur',
    worldId: 'light',
    nameJa: 'アーサー王',
    nameZh: '亚瑟王',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/light-guardian6.png',
    descriptionJa: '聖剣エクスカリバーを掲げる伝説の騎士。光輝なる王道を歩み、騎士たちの絆を導く。',
    unlockCondition: '光の城 Stage 6 をクリア',
    reviewMode: 'timedReview',
  },
  {
    id: 'light-guardian-joan',
    worldId: 'light',
    nameJa: 'ジャンヌ・ダルク',
    nameZh: '圣女贞德',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/light-guardian7.png',
    descriptionJa: '聖なる啓示に従い戦場を駆ける救国の乙女。揺るぎない信仰と光の旗印で、人々を鼓舞する。',
    unlockCondition: '光の城 Stage 7 をクリア',
    reviewMode: 'cloze',
  },
  {
    id: 'light-guardian-zhuge',
    worldId: 'light',
    nameJa: '諸葛孔明',
    nameZh: '诸葛孔明',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/light-guardian8.png',
    descriptionJa: '天下の行く末を見通す稀代の智将。神算鬼謀の計略と、透徹した知恵の光で勝利を導く。',
    unlockCondition: '光の城 Stage 8 をクリア',
    reviewMode: 'sentence',
  },
  {
    id: 'light-boss-zeus',
    worldId: 'light',
    nameJa: 'ゼウス',
    nameZh: '宙斯',
    type: 'boss',
    rarity: 'LEGEND',
    image: '/assets/eigo-quest/cards/light-guardian9.png',
    descriptionJa: '全宇宙を統べる全知全能の最高神。雷霆の輝きを放ち、絶対的な威厳で秩序を支配する。',
    unlockCondition: '光の城 Stage 9 をクリア',
    reviewMode: 'vocabExpansion',
  },
  {
    id: 'light-boss-lucifer',
    worldId: 'light',
    nameJa: 'ルシファー',
    nameZh: '路西法',
    type: 'boss',
    rarity: 'LEGEND',
    image: '/assets/eigo-quest/cards/light-guardian10.png',
    descriptionJa: 'かつて天界で最も美しく輝いた、光をもたらす者。その誇り高き光芒は今も失われていない。',
    unlockCondition: '光の城 Boss Stage をクリア',
    reviewMode: 'finalBoss',
  },

  // ==========================================
  // ROCK WORLD (岩の世界) - Total: 10 Cards
  // ==========================================
  {
    id: 'rock-guardian-gaia',
    worldId: 'rock',
    nameJa: 'ガイア',
    nameZh: '盖亚',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/rock-guardian1.png',
    descriptionJa: '大地を司るギリシャの女神。万物の母であり、大地の底知れぬ力で世界を包み込む。',
    unlockCondition: '岩の谷 Stage 1 をクリア',
    reviewMode: 'dailyReview',
  },
  {
    id: 'rock-monster-behemoth',
    worldId: 'rock',
    nameJa: 'ベヒモス',
    nameZh: '贝希摩斯',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/rock-guardian2.png',
    descriptionJa: '大地を震わせる巨獣。その巨大な体躯と岩石のような皮膚で、あらゆる攻撃を跳ね返す。',
    unlockCondition: '岩の谷 Stage 2 をクリア',
    reviewMode: 'wrongWords',
  },
  {
    id: 'rock-guardian-hades',
    worldId: 'rock',
    nameJa: 'ハデス',
    nameZh: '哈迪斯',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/rock-guardian3.png',
    descriptionJa: '冥界と地中の富を司る神。冷徹な意志の光で、深い闇の底にある秩序を守る。',
    unlockCondition: '岩の谷 Stage 3 をクリア',
    reviewMode: 'weakness',
  },
  {
    id: 'rock-guardian-forseti',
    worldId: 'rock',
    nameJa: 'フォルセティ',
    nameZh: '凡赛堤',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/rock-guardian4.png',
    descriptionJa: '正義と裁判を司る北欧の神。泰山のごとき公正さで、大地の法と秩序を厳格に裁定する。',
    unlockCondition: '岩の谷 Stage 4 をクリア',
    reviewMode: 'quiz',
  },
  {
    id: 'rock-guardian-prithvi',
    worldId: 'rock',
    nameJa: 'プリティヴィー',
    nameZh: '帝哩提微',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/rock-guardian5.png',
    descriptionJa: '大地を神格化したインドの女神。豊穣なる大地の恵みを与え、すべての生命を支える。',
    unlockCondition: '岩の谷 Stage 5 をクリア',
    reviewMode: 'multipleChoice',
  },
  {
    id: 'rock-guardian-guanxiu',
    worldId: 'rock',
    nameJa: '張飛',
    nameZh: '张飞',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/rock-guardian6.png',
    descriptionJa: '万人の敵と称された三国の豪傑。当陽橋の咆哮は長坂をも震わせ、岩のごとき不動の勇姿を誇る。',
    unlockCondition: '岩の谷 Stage 6 をクリア',
    reviewMode: 'timedReview',
  },
  {
    id: 'rock-guardian-houji',
    worldId: 'rock',
    nameJa: '后稷',
    nameZh: '后稷',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/rock-guardian7.png',
    descriptionJa: '農耕と大地を司る中国神話の神。土を耕し、人々に農耕の知恵を授けた大地の開拓者。',
    unlockCondition: '岩の谷 Stage 7 をクリア',
    reviewMode: 'cloze',
  },
  {
    id: 'rock-guardian-iyeyasu',
    worldId: 'rock',
    nameJa: '徳川家康',
    nameZh: '德川家康',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/rock-guardian8.png',
    descriptionJa: '天下を平定し江戸幕府を開いた宿老。泰山のごとき忍耐強さで時を待ち、堅実な基盤を築く。',
    unlockCondition: '岩の谷 Stage 8 をクリア',
    reviewMode: 'sentence',
  },
  {
    id: 'rock-guardian-ohyamatsumi',
    worldId: 'rock',
    nameJa: 'オオヤマツミ',
    nameZh: '大山津见',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/rock-guardian9.png',
    descriptionJa: 'すべての山々を統べる日本神話の山の神。険しい山脈と大自然の威厳をもって世界を守護する。',
    unlockCondition: '岩の谷 Stage 9 をクリア',
    reviewMode: 'vocabExpansion',
  },
  {
    id: 'rock-boss-shiva',
    worldId: 'rock',
    nameJa: 'シヴァ',
    nameZh: '湿婆',
    type: 'boss',
    rarity: 'LEGEND',
    image: '/assets/eigo-quest/cards/rock-guardian10.png',
    descriptionJa: '破壊と再生を司る最高神。その圧倒的な神力は三界を揺るがし、絶対的な力で終焉をもたらす。',
    unlockCondition: '岩の谷 Boss Stage をクリア',
    reviewMode: 'boss',
  },

  // ==========================================
  // SHADOW WORLD (影の世界) - Total: 10 Cards
  // ==========================================
  {
    id: 'shadow-guardian-nyx',
    worldId: 'shadow',
    nameJa: 'ニュクス',
    nameZh: '尼克斯',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/shadow-guardian1.png',
    descriptionJa: '夜を司るギリシャの女神。万物に先駆けて生まれ、漆黒の夜の帳で世界を優しく包み込む。',
    unlockCondition: '影の迷宮 Stage 1 をクリア',
    reviewMode: 'synonym',
  },
  {
    id: 'shadow-monster-fenrir',
    worldId: 'shadow',
    nameJa: 'フェンリル',
    nameZh: '芬里尔',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/shadow-guardian2.png',
    descriptionJa: '全てを呑み込む巨大な魔狼。その底知れぬ飢えと凶暴さで、夜の平穏を脅かす影の化身。',
    unlockCondition: '影の迷宮 Stage 2 をクリア',
    reviewMode: 'antonym',
  },
  {
    id: 'shadow-guardian-hel',
    worldId: 'shadow',
    nameJa: 'ヘル',
    nameZh: '海拉',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/shadow-guardian3.png',
    descriptionJa: '冥府を統べる北欧の女神。生と死の境界に立ち、静寂のなかで死者の魂を静かに導く。',
    unlockCondition: '影の迷宮 Stage 3 をクリア',
    reviewMode: 'vocabExpansion',
  },
  {
    id: 'shadow-guardian-hypnos',
    worldId: 'shadow',
    nameJa: 'ヒュプノス',
    nameZh: '修普诺斯',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/shadow-guardian4.png',
    descriptionJa: '眠りを司るギリシャの神. 穏やかな羽ばたきで人々に安らぎの夢をもたらす。',
    unlockCondition: '影の迷宮 Stage 4 をクリア',
    reviewMode: 'quiz',
  },
  {
    id: 'shadow-guardian-kali',
    worldId: 'shadow',
    nameJa: 'カーリー',
    nameZh: '迦梨',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/shadow-guardian5.png',
    descriptionJa: '破壊と時間を司るインドの女神。漆黒の肌をまとい、圧倒的な荒ぶる力で悪を滅ぼす。',
    unlockCondition: '影の迷宮 Stage 5 をクリア',
    reviewMode: 'multipleChoice',
  },
  {
    id: 'shadow-guardian-simayi',
    worldId: 'shadow',
    nameJa: '司馬懿',
    nameZh: '司马懿',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/shadow-guardian6.png',
    descriptionJa: '深謀遠慮をもって大局を制した三国の智将。影に潜む狼のごとき執念で時を待ち、覇業を成す。',
    unlockCondition: '影の迷宮 Stage 6 をクリア',
    reviewMode: 'timedReview',
  },
  {
    id: 'shadow-guardian-chiyou',
    worldId: 'shadow',
    nameJa: '蚩尤',
    nameZh: '蚩尤',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/shadow-guardian7.png',
    descriptionJa: '戦を司る中国神話の武神。濃霧を操り敵の目を眩ませる、恐るべき影の軍勢の統率者。',
    unlockCondition: '影の迷宮 Stage 7 をクリア',
    reviewMode: 'cloze',
  },
  {
    id: 'shadow-guardian-hanchou',
    worldId: 'shadow',
    nameJa: '服部半蔵',
    nameZh: '服部半藏',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/shadow-guardian8.png',
    descriptionJa: '影に生き、影に消える伝説の忍び。绝对の忠誠を胸に、闇から主君の覇道を支える。',
    unlockCondition: '影の迷宮 Stage 8 をクリア',
    reviewMode: 'sentence',
  },
  {
    id: 'shadow-guardian-tsukuyomi',
    worldId: 'shadow',
    nameJa: 'ツクヨミ',
    nameZh: '月读命',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/shadow-guardian9.png',
    descriptionJa: '夜の国を統べる日本神話の月の神。静寂なる輝きを放ち、夜の秩序と影の調和を守る。',
    unlockCondition: '影の迷宮 Stage 9 をクリア',
    reviewMode: 'challenge',
  },
  {
    id: 'shadow-boss-anubis',
    worldId: 'shadow',
    nameJa: 'アヌビス',
    nameZh: '阿努比斯',
    type: 'boss',
    rarity: 'LEGEND',
    image: '/assets/eigo-quest/cards/shadow-guardian10.png',
    descriptionJa: '冥界の審判を司る天秤の守護神。死者の魂の重さを測り、厳格なる真実の裁きを下す。',
    unlockCondition: '影の迷宮 Boss Stage をクリア',
    reviewMode: 'boss',
  },

  // ==========================================
  // THUNDER WORLD (雷の世界) - Total: 10 Cards
  // ==========================================
  {
    id: 'thunder-guardian-thor',
    worldId: 'thunder',
    nameJa: 'トール',
    nameZh: '托尔',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/thunder-guardian1.png',
    descriptionJa: '雷と力を司る北欧の英雄神。最強の神槌ミョルニルを振るい、迫り来る巨人の軍勢を打ち砕く。',
    unlockCondition: '雷の荒野 Stage 1 をクリア',
    reviewMode: 'speedQuiz',
  },
  {
    id: 'thunder-monster-nue',
    worldId: 'thunder',
    nameJa: '鵺',
    nameZh: '鵺',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/thunder-guardian2.png',
    descriptionJa: '黒煙とともに現れる伝説の怪鳥。不気味な鳴き声で雷雲を呼び寄せ、人心を惑わす。',
    unlockCondition: '雷の荒野 Stage 2 をクリア',
    reviewMode: 'listening',
  },
  {
    id: 'thunder-guardian-perun',
    worldId: 'thunder',
    nameJa: 'ペルーン',
    nameZh: '佩伦',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/thunder-guardian3.png',
    descriptionJa: '雷霆と嵐を統べるスラヴの最高神。正義の雷を放ち、地上のあらゆる邪悪を焼き尽くす。',
    unlockCondition: '雷の荒野 Stage 3 をクリア',
    reviewMode: 'timedReview',
  },
  {
    id: 'thunder-guardian-baron',
    worldId: 'thunder',
    nameJa: 'バロン',
    nameZh: '巴隆',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/thunder-guardian4.png',
    descriptionJa: '聖獣と称されるバリ神話の善の化身。強大な霊力と雷鸣のような咆哮で、魔女ランダを退ける。',
    unlockCondition: '雷の荒野 Stage 4 をクリア',
    reviewMode: 'quiz',
  },
  {
    id: 'thunder-guardian-indra',
    worldId: 'thunder',
    nameJa: 'インドラ',
    nameZh: '因陀罗',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/thunder-guardian5.png',
    descriptionJa: '雷霆を操るインドの英雄神。神々の王として、天を割る稲妻の一撃で闇の軍勢を讨ち払う。',
    unlockCondition: '雷の荒野 Stage 5 をクリア',
    reviewMode: 'multipleChoice',
  },
  {
    id: 'thunder-guardian-guanyu',
    worldId: 'thunder',
    nameJa: '関羽',
    nameZh: '关羽',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/thunder-guardian6.png',
    descriptionJa: '義勇に生き、武神と崇められた三国の英傑。青龍偃月刀の一閃は雷光のごとく激しく、敵陣を震え上がらせる。',
    unlockCondition: '雷の荒野 Stage 6 をクリア',
    reviewMode: 'fastListening',
  },
  {
    id: 'thunder-guardian-leizhenzi',
    worldId: 'thunder',
    nameJa: '雷震子',
    nameZh: '雷震子',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/thunder-guardian7.png',
    descriptionJa: '雷の翼を持つ中国神話の戦士。天の雷を自在に操り、戦場に激烈な電光をもたらす。',
    unlockCondition: '雷の荒野 Stage 7 をクリア',
    reviewMode: 'cloze',
  },
  {
    id: 'thunder-guardian-shingen',
    worldId: 'thunder',
    nameJa: '武田信玄',
    nameZh: '武田信玄',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/thunder-guardian8.png',
    descriptionJa: '「甲斐の虎」と恐れられた戦国の名将。「動くこと雷霆の如し」の兵法を体現し、圧倒的な速攻で蹂躙する。',
    unlockCondition: '雷の荒野 Stage 8 をクリア',
    reviewMode: 'sentence',
  },
  {
    id: 'thunder-guardian-takemikazuchi',
    worldId: 'thunder',
    nameJa: 'タケミカヅチ',
    nameZh: '建御雷神',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/thunder-guardian9.png',
    descriptionJa: '日本神話における雷の武神。鋭き十握剣を構え、轟く雷鳴とともに国譲りの大功を立てる。',
    unlockCondition: '雷の荒野 Stage 9 をクリア',
    reviewMode: 'vocabExpansion',
  },
  {
    id: 'thunder-boss-susanoo',
    worldId: 'thunder',
    nameJa: 'スサノオ',
    nameZh: '须佐之男',
    type: 'boss',
    rarity: 'LEGEND',
    image: '/assets/eigo-quest/cards/thunder-guardian10.png',
    descriptionJa: '嵐と荒ぶる力を支配する日本神話の英雄。十拳剣を振るい、八岐大蛇をも打ち滅ぼす神威を宿す。',
    unlockCondition: '雷の荒野 Boss Stage をクリア',
    reviewMode: 'boss',
  },

  // ==========================================
  // WATER WORLD (水の世界) - Total: 10 Cards
  // ==========================================
  {
    id: 'water-guardian-poseidon',
    worldId: 'water',
    nameJa: 'ポセイドン',
    nameZh: '波塞冬',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/water-guardian1.png',
    descriptionJa: '海と嵐を司るギリシャの神。三叉戟を振るい、大洋を震わせ、荒波を自在に操る。',
    unlockCondition: '水の港 Stage 1 をクリア',
    reviewMode: 'listening',
  },
  {
    id: 'water-monster-kraken',
    worldId: 'water',
    nameJa: 'クラーケン',
    nameZh: '克拉肯',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/water-guardian2.png',
    descriptionJa: '深海に潜む伝説の巨大な怪獣。無数の触手で渦潮を起こし、船乗りたちを絶望の淵へ引きずり込む。',
    unlockCondition: '水の港 Stage 2 をクリア',
    reviewMode: 'quiz',
  },
  {
    id: 'water-guardian-aegir',
    worldId: 'water',
    nameJa: 'エーギル',
    nameZh: '埃吉尔',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/water-guardian3.png',
    descriptionJa: '深海を統べる北欧の海洋神。海の底の宮殿で波を支配し、時に荒々しく牙を剥く。',
    unlockCondition: '水の港 Stage 3 をクリア',
    reviewMode: 'multipleChoice',
  },
  {
    id: 'water-guardian-njord',
    worldId: 'water',
    nameJa: 'ニョルズ',
    nameZh: '尼奥尔德',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/water-guardian4.png',
    descriptionJa: '海と風、そして航海を司る北欧の神。穏やかな波を呼び寄せ、旅人の航路を優しく守護する。',
    unlockCondition: '水の港 Stage 4 をクリア',
    reviewMode: 'cloze',
  },
  {
    id: 'water-guardian-varuna',
    worldId: 'water',
    nameJa: 'ヴァルナ',
    nameZh: '伐楼那',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/water-guardian5.png',
    descriptionJa: '宇宙の法と聖なる水を司るインドの最高神。広大な天海から、世界の調和を厳格に見守る。',
    unlockCondition: '水の港 Stage 5 をクリア',
    reviewMode: 'timedReview',
  },
  {
    id: 'water-guardian-zhouyu',
    worldId: 'water',
    nameJa: '周瑜',
    nameZh: '周瑜',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/water-guardian6.png',
    descriptionJa: '赤壁の戦いで大破を指揮した三国の水軍都督。大河を舞台にした神算鬼謀の計略で、勝利の波を掴み取る。',
    unlockCondition: '水の港 Stage 6 をクリア',
    reviewMode: 'sentence',
  },
  {
    id: 'water-guardian-gonggong',
    worldId: 'water',
    nameJa: '共工',
    nameZh: '共工',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/water-guardian7.png',
    descriptionJa: '洪水を操る中国神話の水神。激しい気性と圧倒的な水力で、天地を揺るがす大氾濫を起こす。',
    unlockCondition: '水の港 Stage 7 をクリア',
    reviewMode: 'vocabExpansion',
  },
  {
    id: 'water-guardian-kenshin',
    worldId: 'water',
    nameJa: '上杉謙信',
    nameZh: '上杉谦信',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/water-guardian8.png',
    descriptionJa: '「越後の龍」と称された義の戦国大名。その軍略は流れる水のごとく淀みなく、臨機応変に敵を圧倒する。',
    unlockCondition: '水の港 Stage 8 をクリア',
    reviewMode: 'challenge',
  },
  {
    id: 'water-guardian-watatsumi',
    worldId: 'water',
    nameJa: 'ワタツミ',
    nameZh: '绵津见',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/water-guardian9.png',
    descriptionJa: '海のすべてを総べる日本神話の海の主神。神秘の潮満珠と潮干珠を操り、広大な海原の秩序を統治する。',
    unlockCondition: '水の港 Stage 9 をクリア',
    reviewMode: 'fastListening',
  },
  {
    id: 'water-boss-leviathan',
    worldId: 'water',
    nameJa: 'レヴィアタン',
    nameZh: '利维坦',
    type: 'boss',
    rarity: 'LEGEND',
    image: '/assets/eigo-quest/cards/water-guardian10.png',
    descriptionJa: '混沌たる大海を支配する巨大な海の怪物。その巨体から繰り出される激流は、万物を飲み込む終末の化身。',
    unlockCondition: '水の港 Boss Stage をクリア',
    reviewMode: 'boss',
  },

  // ==========================================
  // WIND WORLD (风の世界) - Total: 10 Cards
  // ==========================================
  {
    id: 'wind-guardian-zephyrus',
    worldId: 'wind',
    nameJa: 'ゼピュロス',
    nameZh: '西风之神',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wind-guardian1.png',
    descriptionJa: '西風を司るギリシャの神。春の訪れを告げる穏やかな風で、大自然の生命を優しく目覚めさせる。',
    unlockCondition: '風の区域 Stage 1 をクリア',
    reviewMode: 'listening',
  },
  {
    id: 'wind-monster-griffin',
    worldId: 'wind',
    nameJa: 'グリフォン',
    nameZh: '狮鹫',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/wind-guardian2.png',
    descriptionJa: '黄金の宝を守る伝説的獣。鷲の翼とライオンの身体を持ち、天空から鋭い爪で襲いかかる。',
    unlockCondition: '風の区域 Stage 2 をクリア',
    reviewMode: 'flashcard',
  },
  {
    id: 'wind-guardian-odin',
    worldId: 'wind',
    nameJa: 'オーディン',
    nameZh: '奥丁',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/wind-guardian3.png',
    descriptionJa: '嵐と知恵を司る北欧の最高神。愛馬スレイプニルに跨り、天空を駆け抜け世界の全てを見通す。',
    unlockCondition: '風の区域 Stage 3 をクリア',
    reviewMode: 'speedQuiz',
  },
  {
    id: 'wind-guardian-hraesvelgr',
    worldId: 'wind',
    nameJa: 'フレースヴェルグ',
    nameZh: '赫拉斯瓦尔格',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wind-guardian4.png',
    descriptionJa: '世界の果てに座す巨鷹の姿をした巨人。大いなる羽ばたきによって、世界に吹き荒れる風を生み出す。',
    unlockCondition: '風の区域 Stage 4 をクリア',
    reviewMode: 'quiz',
  },
  {
    id: 'wind-guardian-vayu',
    worldId: 'wind',
    nameJa: 'ヴァーユ',
    nameZh: '筏由',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wind-guardian5.png',
    descriptionJa: '風と大気を司るインドの神。目に見えぬ一迅の風となり、圧倒的な素早さで戦場を駆け抜ける。',
    unlockCondition: '風の区域 Stage 5 をクリア',
    reviewMode: 'multipleChoice',
  },
  {
    id: 'wind-guardian-zhaoyun',
    worldId: 'wind',
    nameJa: '趙雲',
    nameZh: '赵云',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/wind-guardian6.png',
    descriptionJa: '疾風怒濤の如く戦場を駆ける三国の英傑。長坂坡を単騎で突破するその姿は、まさに一陣の白风。',
    unlockCondition: '風の区域 Stage 6 をクリア',
    reviewMode: 'timedReview',
  },
  {
    id: 'wind-guardian-feilian',
    worldId: 'wind',
    nameJa: '飛廉',
    nameZh: '飞廉',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wind-guardian7.png',
    descriptionJa: '風を操る中国神話の風神。鳥の頭と鹿の身体を持ち、袋から猛烈な暴風を吹き出させる。',
    unlockCondition: '風の区域 Stage 7 をクリア',
    reviewMode: 'cloze',
  },
  {
    id: 'wind-guardian-masamune',
    worldId: 'wind',
    nameJa: '伊達政宗',
    nameZh: '伊达政宗',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/wind-guardian8.png',
    descriptionJa: '「独眼竜」と恐れられた奥州の覇者。時代の風を読み解く鋭い先見性と、新風を巻き起こす機動力を持つ。',
    unlockCondition: '風の区域 Stage 8 をクリア',
    reviewMode: 'sentence',
  },
  {
    id: 'wind-guardian-shinato',
    worldId: 'wind',
    nameJa: 'シナトベ',
    nameZh: '志那都比古神',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/wind-guardian9.png',
    descriptionJa: '日本神話における風の神。息吹から強烈な神風を生み出し、世界の穢れを一気に吹き払う。',
    unlockCondition: '風の区域 Stage 9 をクリア',
    reviewMode: 'vocabExpansion',
  },
  {
    id: 'wind-boss-typhoeus',
    worldId: 'wind',
    nameJa: 'テュポーン',
    nameZh: '堤丰',
    type: 'boss',
    rarity: 'LEGEND',
    image: '/assets/eigo-quest/cards/wind-guardian10.png',
    descriptionJa: '星々を揺るがす史上最悪の暴風巨人。巨大な翼で天空を覆い、破滅の大嵐で全てを破壊する最凶の化身。',
    unlockCondition: '風の区域 Boss Stage をクリア',
    reviewMode: 'boss',
  },

  // ==========================================
  // WOOD WORLD (木の世界) - Total: 10 Cards
  // ==========================================
  {
    id: 'wood-guardian-demeter',
    worldId: 'wood',
    nameJa: 'デメテル',
    nameZh: '德墨忒尔',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wood-guardian1.png',
    descriptionJa: '豊穣と大地を司るギリシャの女神。豊かな緑と実りを大地にもたらし、生命の成長を見守る。',
    unlockCondition: '木の森 Stage 1 をクリア',
    reviewMode: 'grammar',
  },
  {
    id: 'wood-monster-alraune',
    worldId: 'wood',
    nameJa: 'アルラウネ',
    nameZh: '阿尔拉曼',
    type: 'monster',
    rarity: 'R',
    image: '/assets/eigo-quest/cards/wood-guardian2.png',
    descriptionJa: '深い森の奥に咲く伝説の妖花。魅惑的な香りと絡みつく蔦で、迷い込んだ旅人の行く手を阻む。',
    unlockCondition: '木の森 Stage 2 をクリア',
    reviewMode: 'quiz',
  },
  {
    id: 'wood-guardian-vidar',
    worldId: 'wood',
    nameJa: 'ヴィーザル',
    nameZh: '维达',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wood-guardian3.png',
    descriptionJa: '森と沈黙を司る北欧の神。大自然の静寂なる力を宿し、強靭な意志で絶望の淵から立ち上がる。',
    unlockCondition: '木の森 Stage 3 をクリア',
    reviewMode: 'multipleChoice',
  },
  {
    id: 'wood-guardian-idun',
    worldId: 'wood',
    nameJa: 'イズン',
    nameZh: '伊登',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wood-guardian4.png',
    descriptionJa: '春と若さを保つ北欧の女神。黄金の林檎を管理し、神々に永遠の生命力と瑞々しい輝きを与える。',
    unlockCondition: '木の森 Stage 4 をクリア',
    reviewMode: 'cloze',
  },
  {
    id: 'wood-guardian-soma',
    worldId: 'wood',
    nameJa: 'ソーマ',
    nameZh: '苏摩',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wood-guardian5.png',
    descriptionJa: '植物と神秘の液を司るインドの神。万物を滋養する瑞々しい生命のしずくで、森の調和を維持する。',
    unlockCondition: '木の森 Stage 5 をクリア',
    reviewMode: 'timedReview',
  },
  {
    id: 'wood-guardian-liubei',
    worldId: 'wood',
    nameJa: '劉備',
    nameZh: '刘备',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/wood-guardian6.png',
    descriptionJa: '大徳をもって人々を率いた三国の英傑。大樹が大地に深く根を張るように、揺るぎない仁義の心で絆を紡ぐ。',
    unlockCondition: '木の森 Stage 6 をクリア',
    reviewMode: 'sentence',
  },
  {
    id: 'wood-guardian-shennong',
    worldId: 'wood',
    nameJa: '神農',
    nameZh: '神农',
    type: 'guardian',
    rarity: 'SR',
    image: '/assets/eigo-quest/cards/wood-guardian7.png',
    descriptionJa: '農耕と医薬を司る中国神話の始祖。百草を舐めて薬効を確かめ、人々に大自然の恵みと知恵を授けた。',
    unlockCondition: '木の森 Stage 7 をクリア',
    reviewMode: 'vocabExpansion',
  },
  {
    id: 'wood-guardian-motonari',
    worldId: 'wood',
    nameJa: '毛利元就',
    nameZh: '毛利元就',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/wood-guardian8.png',
    descriptionJa: '「三本の矢」の教えで知られる戦国の智将。一木では折れやすくとも、集えば森のごとき結束の力を生む。',
    unlockCondition: '木の森 Stage 8 をクリア',
    reviewMode: 'challenge',
  },
  {
    id: 'wood-guardian-sukunabikona',
    worldId: 'wood',
    nameJa: 'スクナヒコナ',
    nameZh: '少彦名神',
    type: 'guardian',
    rarity: 'SSR',
    image: '/assets/eigo-quest/cards/wood-guardian9.png',
    descriptionJa: '常世の国から訪れた国造りの小さな神。豊かな医薬や穀物の知恵をもたらし、大地に緑の生気を与える。',
    unlockCondition: '木の森 Stage 9 をクリア',
    reviewMode: 'grammarForm',
  },
  {
    id: 'wood-boss-ygdrasil',
    worldId: 'wood',
    nameJa: 'ユグドラシル',
    nameZh: '尤克特拉希尔',
    type: 'boss',
    rarity: 'LEGEND',
    image: '/assets/eigo-quest/cards/wood-guardian10.png',
    descriptionJa: '九つの世界をその枝葉に支える伝説の世界樹。万物の根源たる強大な生命力で、世界の秩序を总べる。',
    unlockCondition: '木の森 Boss Stage をクリア',
    reviewMode: 'boss',
  },
];

export default eigoQuestCards;
