export const EIGO_QUEST_WORDS_PER_STAGE = 20;

export const eigoQuestWorlds = [
  {
    id: 'wind',
    order: 1,
    nameJa: '風の区域',
    nameZh: '风之区域',
    subtitleJa: '音を聞き取り、単語をすばやく覚える冒険',
    themeColor: '#35d9ff',
    backgroundImage: '/assets/eigo-quest/worlds/wind.png',
    icon: '風',
    learningFocus: 'リスニング・発音・単語カード',
    stageCount: 10,
    wordCount: 200,
    wordStartIndex: 0,
    stages: 10,
  },
  {
    id: 'fire',
    order: 2,
    nameJa: '火の山',
    nameZh: '火之山',
    subtitleJa: 'クイズで知識を燃やして強くする冒険',
    themeColor: '#ff6b8a',
    backgroundImage: '/assets/eigo-quest/worlds/fire.png',
    icon: '火',
    learningFocus: '単語クイズ・復習',
    stageCount: 10,
    wordCount: 200,
    wordStartIndex: 200,
    stages: 10,
  },
  {
    id: 'water',
    order: 3,
    nameJa: '水の港',
    nameZh: '水之港',
    subtitleJa: '音声と文章をつなぎ、理解を深める冒険',
    themeColor: '#35d9ff',
    backgroundImage: '/assets/eigo-quest/worlds/water.png',
    icon: '水',
    learningFocus: 'リスニング・英検語彙',
    stageCount: 10,
    wordCount: 200,
    wordStartIndex: 400,
    stages: 10,
  },
  {
    id: 'thunder',
    order: 4,
    nameJa: '雷の塔',
    nameZh: '雷之塔',
    subtitleJa: 'すばやく選び、正確に答える冒険',
    themeColor: '#ffd35a',
    backgroundImage: '/assets/eigo-quest/worlds/thunder.png',
    icon: '雷',
    learningFocus: '四択問題・瞬間判断',
    stageCount: 10,
    wordCount: 200,
    wordStartIndex: 600,
    stages: 10,
  },
  {
    id: 'wood',
    order: 5,
    nameJa: '木の森',
    nameZh: '木之森林',
    subtitleJa: '例文を読んで言葉の使い方を育てる冒険',
    themeColor: '#54e6a8',
    backgroundImage: '/assets/eigo-quest/worlds/wood.png',
    icon: '木',
    learningFocus: '例文・意味理解',
    stageCount: 10,
    wordCount: 200,
    wordStartIndex: 800,
    stages: 10,
  },
  {
    id: 'rock',
    order: 6,
    nameJa: '岩の谷',
    nameZh: '岩之谷',
    subtitleJa: 'こつこつ積み上げて苦手をなくす冒険',
    themeColor: '#b7c0dd',
    backgroundImage: '/assets/eigo-quest/worlds/rock.png',
    icon: '岩',
    learningFocus: 'まちがい直し・弱点復習',
    stageCount: 10,
    wordCount: 200,
    wordStartIndex: 1000,
    stages: 10,
  },
  {
    id: 'light',
    order: 7,
    nameJa: '光の城',
    nameZh: '光之城',
    subtitleJa: '文法と英検に挑戦する終盤の冒険',
    themeColor: '#ffd35a',
    backgroundImage: '/assets/eigo-quest/worlds/light.png',
    icon: '光',
    learningFocus: '文法練習・英検チャレンジ',
    stageCount: 10,
    wordCount: 200,
    wordStartIndex: 1200,
    stages: 10,
  },
  {
    id: 'shadow',
    order: 8,
    nameJa: '影の迷宮',
    nameZh: '影之迷宫',
    subtitleJa: 'まぎらわしい言葉を見分ける最後の冒険',
    themeColor: '#7b55ff',
    backgroundImage: '/assets/eigo-quest/worlds/shadow.png',
    icon: '影',
    learningFocus: '類義語・対義語',
    stageCount: 5,
    wordCount: 100,
    wordStartIndex: 1400,
    stages: 5,
  },
];

export const EIGO_QUEST_TOTAL_WORDS = eigoQuestWorlds.reduce((total, world) => total + world.wordCount, 0);
export const EIGO_QUEST_TOTAL_STAGES = eigoQuestWorlds.reduce((total, world) => total + world.stageCount, 0);
export const EIGO_QUEST_WORLD_ORDER = eigoQuestWorlds.map((world) => world.id);

export function getEigoQuestWorld(worldId) {
  return eigoQuestWorlds.find((world) => world.id === worldId) || null;
}

export default eigoQuestWorlds;
